package com.hrishi.restspringproject.springrestservice.beans;

import java.util.Date;

import javax.validation.constraints.Past;
import javax.validation.constraints.Size;

//import io.swagger.annotations.ApiModel;
//import io.swagger.annotations.ApiModelProperty;
//
//@ApiModel(description = "All the details about the user")
public class User {

//	@ApiModelProperty(notes = "Autogenerated.")
	private Integer id;
	
	@Size(min=2, message="Name should have atleast two characters.")
//	@ApiModelProperty(notes = "Should be minimum two characters.")
	private String name;
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getBirthDate() {
		return birthDate;
	}

	@Override
	public String toString() {
		return "User [id=" + id + ", name=" + name + ", birthDate=" + birthDate + "]";
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Past(message = "The date of birth should be a past date.")
//	@ApiModelProperty(notes = "Birth date cannot be a past date.")
	private Date birthDate;
	
	public User(Integer id, String name, Date date) {
		this.id = id;
		this.name = name;
		this.birthDate = date;
	}
	
	public User() {
	}

}
